[package]
name = "lumin/framework"
description = "A lightning fast & lightweight game framework for Roblox"
version = "7.0.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = [
	"default.project.json",
	"src",
	"src/**",
	"LICENSE",
	"wally.toml",
	"README.md",
]

[dependencies]
future = "red-blox/future@1.0.1"
spawn = "red-blox/spawn@1.0.0"
event = "red-blox/signal@2.0.2"
ratelimit = "red-blox/ratelimit@1.0.1"
red = "lolmansreturn/red-backend@1.2.7"

[place]
shared-packages = "game.ReplicatedStorage.Packages"
